### ISSUE TITLE
not working on window 8 32 bit

### ISSUE THREAD

**Issue by praveenyadav1602** [sevagas/macro_pack#1]
i am using windows 8 32 bit on virtualbox.

results
This version of C:\Users\win8\Desktop\macro_pack.exe is not compatible with the
version of Windows you're running. Check your computer's system information and
then contact the software publisher.

**Comment by sevagas** [comment]
Hi, the macro_pack.exe binaries you can find in https://github.com/sevagas/macro_pack/releases are 64bit binaries only. I do not plan to release compiled 32bit binaries.
If you want 32 bit binary, you need to build it by installing required libs and running "build.bat"
See instruction in README file.
Regards,
Emeric

**Comment by praveenyadav1602** [comment]
thanks. and  how much price for pro
