### ISSUE TITLE
EMBED_EXE not working

### ISSUE THREAD

**Issue by praveenyadav1602** [sevagas/macro_pack#2]
template is inspired by https://github.com/khr0x40sh/MacroShop not working.

and why you change uses options:
before one day ago it was:
`echo "path\\to\my_exe.exe" | macro_pack.exe -t EMBED_EXE -o -X my_exe.xlsm`
now:
`echo "path\\to\my_exe.exe" | macro_pack.exe -t EMBED_EXE -o -G my_exe.xlsm`

you replaced **X** with **G**

tried with both options non worked:

# ***
**try1 with options:**
`echo "path\\to\calc.exe" | macro_pack.exe -t EMBED_EXE -o -x my_exe.xls
**RESULT:**
sucessfully generated my_exe.xls, but not executing calc.exe on opening my_exe.xls, so i opened this workbook to see is there any fault with my vba code , and i surprised that there are only few lines of vba:
screenshot:
http://blog.caddman.com/gitmp/Capture.JPG

so where is base64 strings?

# ***
**try2 with new options that changed before a day ago:**

`echo "path\\to\my_exe.exe" | macro_pack.exe -t EMBED_EXE -o -G my_exe.xlsm`

options with **G** are invalid option

**Comment by sevagas** [comment]
Hi,
I did a major refactoring to simplify document generation.
Now all you need to do  is use -G and macro_pack will guess format based on extension. This simplifies user input.
The -G option was just released on the trunk so it is not available in 1.1 release.
You can get it if you clone the trunk and build macro_pack.
-G option will be delivered in 1.2

Concerning EMBED_EXE:
- The launched exe is hidden (this is meant to launch stealth droppers for example)
 Calc would not appear but you should see it in task manager
- Currently is does not work for exe bigger than 1mega I will open an issue for that
I am going to investigate more on EMBED_EXE later in the day

Concerning macro_pack pro related questions, please email  at emeric.nasi[ at ]sevagas.com or at ena.sevagas[ at ]protonmail.com

**Comment by sevagas** [comment]
For me it does not work with calc because of the size problem (I opened issue for that).
Could you try with a small exe and tell me if it appear in task manager?  
For  info you can also just generate the obfuscated vba doing:
`echo "c:\Windows\System32\calc.exe" | python macro_pack.py -t EMBED_EXE -o -G calc.vba`

**Comment by sevagas** [comment]
I did investigate, it seem EMBED_EXE is broken. test which used to work do not anymore.
I will correct this issue before the 1.2 release.

**Comment by praveenyadav1602** [comment]
sorry for late reply, i tried with:
`echo "c:\Windows\System32\calc.exe" | python macro_pack.py -t EMBED_EXE -o -G calc.vba`
vba is good and worked like a charm in office documents as a macro.
screenshot of vba:
http://blog.caddman.com/gitmp/Capture12.JPG

but when i generate .xls from exe 
`echo "path\to\calc.exe" | macro_pack.exe -t EMBED_EXE -o -x my_exe.xls`
and open vba from generated document, there is Half-unfinished vba:
screenshot:
http://blog.caddman.com/gitmp/Capture.JPG

i think problem is with macro_pack.exe

here one warning i get from macro_pack.exe:
http://blog.caddman.com/gitmp/Capture11.JPG

**Comment by sevagas** [comment]
Hi,
In fact EMBED_EXE template did not exist in 1.1 version that is why it is not in the exe :)!
EMBED_EXE and CMD templates are recent 1.2-dev templates.  
On my side this is working:
`echo "c:\Windows\System32\calc.exe" | python macro_pack.py -t EMBED_EXE -o -G calc.vba`

But not this:
`echo "c:\Windows\System32\calc.exe" | python macro_pack.py -t EMBED_EXE -o -G calc.xlsm`

I have to investigate why.
Emeric

**Comment by praveenyadav1602** [comment]
i understand,
ok thanks, for made a great tool.

**Comment by praveenyadav1602** [comment]
one more thing:
generated vba from crypted  and packed .exe not working on any office version, and same problem is with https://github.com/khr0x40sh/MacroShop

in all cases i am using w97-2003 format.

**Comment by sevagas** [comment]
It seems the problems is more complicated than just size.  base 64 encoded string representation sometimes create a problem in the VBA compilation process. A small module containing the wrong chars can prevent the document from being saved. I have no clue why this happens!
