### ISSUE TITLE
where is vbs_gen module !!!

### ISSUE THREAD

**Issue by sparta3407** [sevagas/macro_pack#20]
when i try to launch the script it gives me this error:   

Traceback (most recent call last):
  File "macro_pack.py", line 18, in <module>
    from modules.vbs_gen import VBSGenerator
ImportError: No module named vbs_gen

**Comment by sevagas** [comment]
Sorry got mixed up between repo versions. Am updating now!

**Comment by sparta3407** [comment]
ok thanks
