### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by moaeddy** [sevagas/macro_pack#25]
how can this detection be fixed? its kinda high and its detected as DDE

http://viruscheckmate.com/id/6kJeD3klUvCE

**Comment by sevagas** [comment]
DDE attacks on Ms Word are now disabled by default since https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/ADV170021 
I dont think improving Word DDE feature is worth the time.
(You can still submit a pull request if you want but I will not develop anything related to this myself)

**Comment by mateo24xx** [comment]
how can people in 2018 still use online scanners to test virus..????
for god sake please stop srew everything,it's like shot a bullet in your foot
people do very good job creating great tools and stupid people run to test it on online scanners.

**Comment by moaeddy** [comment]
I can see u are as stupid as ur brain. Is that distribution scan site?  why not check things before making comments who the fuck do u think u are NOOB 2018

**Comment by mateo24xx** [comment]
what a stupid insingifiant litlle person you are ..it is not enough that you are stupid but you are also a finished idiot... OFF COURSE THAT SITE DISTRIBUTE !!ALL ONLINESCANNERS SELL VIRUS TO ANTIVIRUS COMPANYS YOU JERK.....there is to much money to make with stupid people like you..
