### ISSUE TITLE
Support embedding more than one file

### ISSUE THREAD

**Issue by jmhickman** [sevagas/macro_pack#43]
I like your project, and I've played around with it a bit. 

I've been happy with the EMBED_x templates, but when creating a file, I've found it's nice if you can create a legitimate document, as well as running the embedded payload.

For example, if you're phishing via email with an .hta attachment, and the cover is to "decrypt" a secure document, you'd want a real document to appear in the directory the .hta was saved to.

I've manually edited the .hta file to create such an effect, but it would be nice if macro_pack supported this natively by allowing more than one `--embed=` statement.

**Comment by sevagas** [comment]
I agree with that. I will add this feature when I have some time.

**Comment by sevagas** [comment]
I added the feature to embed and trigger decoy payloads. As it is weaponization, its only available in "pro" mode.
