### ISSUE TITLE
ask about macro_pack.py work in linux

### ISSUE THREAD

**Issue by Imanfeng** [sevagas/macro_pack#45]
![2018-11-19 7 22 44](https://user-images.githubusercontent.com/24694387/48704065-965c0b00-ec30-11e8-9aed-8337f2e2ae93.png)
i want to make a doc with macro in linux, can i use this python to make doc?  
thank you

**Comment by Rob2n** [comment]
### Hello @Imanfeng ,
As stated in the [README.md](https://github.com/sevagas/macro_pack/blob/master/README.md) file :
> Windows platform with the right MS Office applications installed is required for Office documents automatic generation or trojan 

Therefore, the available formats for generation under a Linux OS are : 

>  all scripting and shortcuts formats (except LNK)

Here is a list of file formats you can generate with macro_pack under Linux :
- VBA text file (.vba)
- VBS text file (.vbs).
- Windows Script File (.wsf)
- Windows Script Components scriptlets (.wsc, .sct)
- HTML Applications (.hta)
- XSLT Stylesheet (.xsl)
- Explorer Command File (.scf)
- URL Shortcut (.url)
- Groove Shortcuts (.glk)
- Settings Shortcuts (.settingcontent-ms)
- MS Library (.library-ms)
- Setup Information (.inf)
