### ISSUE TITLE
 Encoding error when I use macro_pack.exe to generate .doc

### ISSUE THREAD

**Issue by Imanfeng** [sevagas/macro_pack#46]
Encoding error when I use macro_pack.exe to generate .doc
![2018-11-20 3 20 29](https://user-images.githubusercontent.com/24694387/48757481-d7f3c100-ecd7-11e8-973d-14a609d206e2.png)
![2018-11-20 3 20 37](https://user-images.githubusercontent.com/24694387/48757483-d924ee00-ecd7-11e8-82ca-0d7cb168a335.png)

**Comment by sevagas** [comment]
Hi,
Could you provide the content of the 1.txt file so I can reproduce the issue?

**Comment by sevagas** [comment]
File was not provided. Closing
