### ISSUE TITLE
'gbk' codec can't decode byte 0xc6 in position 18: illegal multibyte sequence

### ISSUE THREAD

**Issue by zhyongquan** [sevagas/macro_pack#47]
![image](https://user-images.githubusercontent.com/11530247/56777233-eb650400-6802-11e9-8e5b-9262a75dea4f.png)

**Comment by sevagas** [comment]
Hi, Sorry I answer that late. Could you provide me the vba file so I can have a look?

**Comment by sevagas** [comment]
No test sample provided. Closing bug.
