### ISSUE TITLE
'gbk' codec can't decode byte 0xba in position 18: illegal multibyte sequence

### ISSUE THREAD

**Issue by supercsj** [sevagas/macro_pack#52]
![image](https://user-images.githubusercontent.com/55480907/65127067-be232780-da29-11e9-9a09-91da62d5b6f2.png)

[vba.zip](https://github.com/sevagas/macro_pack/files/3625025/vba.zip)

**Comment by sevagas** [comment]
What is the command line that you attempted to use?

**Comment by supercsj** [comment]
command line is   macro_pack.exe -f vba.xlsm -o -G vbaO.xlsm

**Comment by supercsj** [comment]
It seems that if there is Chinese character in VBA, this problem will happen

**Comment by sevagas** [comment]
MacroPack cannot take an Excel file in input. It is normal that this command line is not working.
