### ISSUE TITLE
Please add 32 bit release 

### ISSUE THREAD

**Issue by graysuit** [sevagas/macro_pack#53]
`This version of C:\Users\root\Desktop\New folder\macro_pack-master\bin\macro_pack.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

Sir I know this error,Please add 32 bit release files, As I also tried to build but alot of errors come.<br>I know build will take only 2 minutes for coder like you.

**Comment by sevagas** [comment]
I do not plan to provide 32bit macropack binary. This might be done in pro mode if there is a valid usecase.
