### ISSUE TITLE
pywin32 error i can't install it from requirements.txt 

### ISSUE THREAD

**Issue by y1n07** [sevagas/macro_pack#56]
hello , 

when i execute pip install -r requirements.txt i saw this error:

ERROR: Could not find a version that satisfies the requirement pywin32>=225 (from -r requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for pywin32>=225 (from -r requirements.txt (line 8))

i'm using parrot os and the system is updated 

i have both python version installed 

python --version
Python 2.7.18

python3 --version
Python 3.8.5

i noticed a strange error when i tried to run macro_pack too ( i think it has relation with the absence of pywin32 module (?) ) 

python3 macro_pack.py -f test.txt -o -G output/test1.doc

 [+] Preparations...
   [-] Input file path: test.txt
   [-] Target output format: Word97
   [-] Temporary working dir: /home/user/Desktop/macro_pack/src/temp
   [-] Store input file...
   [-] Temporary input file: /home/user/Desktop/macro_pack/src/temp/wojyywplw.vba
 [+] Cleaning...
 Done!

apparently the temp folder  was created but i when i tried to get the obfuscate file wojyywplw.vba 

it  doesn't exist anymore ...

i tried to view hidden files but with no luck ...

what should i do ?

thanks

**Comment by sevagas** [comment]
Hi, MacroPack is supposed to be installed on Windows OS. Also it requires to run on Windows with Office installed to generate Office payloads. I will edit the README so this information is more clear
