### ISSUE TITLE
file detected by windows defender AV

### ISSUE THREAD

**Issue by dxnhkdfkvngextmpuy** [sevagas/macro_pack#58]
this packer can't bypass Windows defender AV 
when the vba script contain execute command such as

```
 Shell(command) or  
Set shell_object = CreateObject("WScript.Shell")
shell_object.Run command ,0,true
```

Windows defender block file with message:
this program is dangerous and execute commands from an attacker

**Comment by sevagas** [comment]
Hi,
MacroPack free version is detected by AV like most public tools. You may try with obfuscation or changing manually some lines of code. Anyway AV bypass is not anymore in the scope of MacroPack free version. The main goal of this tool is to learn.

Only the MacroPack Pro version is maintained and regularly updated with multiple AV and AMSI bypasses.
If you are working for a professional team, you can contact me using your company email address if you are interested by the Pro version.
Regards,
Emeric

**Comment by dxnhkdfkvngextmpuy** [comment]
what is you email ?
