### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 723: character maps to <undefined>

### ISSUE THREAD

**Issue by psychosys** [sevagas/macro_pack#59]
I used the compiled version and got this error 
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 723: character maps to <undefined>
every time I tried ...

I believe you need to add **encoding="utf-8** to your input/output .. I will grab the source and let you know

**Comment by sevagas** [comment]
Hi,
Could you provide the command line you are using when you generated this error?

**Comment by sevagas** [comment]
closing this since no command line provided
