### ISSUE TITLE
ERROR: No matching distribution found for pywin32>=225 (from -r requirements.txt (line 8))

### ISSUE THREAD

**Issue by Akmaling** [sevagas/macro_pack#60]
root@Kali:~/macro_pack# pip install -r requirements.txt
Requirement already satisfied: colorama>=0.4.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.3)
Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: tabulate>=0.8.5 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (0.8.7)
Requirement already satisfied: psutil>=5.6.7 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (5.7.0)
Requirement already satisfied: clr>=1.0.3 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (1.0.3)
Requirement already satisfied: wsgidav>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (3.0.3)
Requirement already satisfied: cheroot>=6.3.3 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (8.4.5)
ERROR: Could not find a version that satisfies the requirement pywin32>=225 (from -r requirements.txt (line 8)) (from versions: none)                                                                                                                 
ERROR: No matching distribution found for pywin32>=225 (from -r requirements.txt (line 8))

Please what am I doing wrong on Kali Linux2020

**Comment by sevagas** [comment]
Hi, MacroPack must be build and executed on a Windows machine
