### ISSUE TITLE
Pro version

### ISSUE THREAD

**Issue by moaeddy** [sevagas/macro_pack#66]
i sent you a personal msg via your email and its been 2weeks now without response. still selling your PRO version? will like to check a test on it

**Comment by sevagas** [comment]
This is not an issue

**Comment by moaeddy** [comment]
i was only trying to get intouch and i have sent you an email but no response. can u acknowledge u ain't selling PRO? then i will ignore this case

**Comment by sevagas** [comment]
Hi, Yes MP Pro is still sold. You have to send an email using your pro email address. Anonymous or non professional requests are generally ignored. Please do not communicate using Github  issues

**Comment by moaeddy** [comment]
pro email address like email i use registered GitHub? kindly clarify

**Comment by sevagas** [comment]
The email address of the company your work for as a security professional. Closing this thread now.
