### ISSUE TITLE
Contains Mimikatz.

### ISSUE THREAD

**Issue by S1m1B1lly** [sevagas/macro_pack#68]

**Comment by Asril666** [comment]
Me too .. When I run the application, windows security detects mimikatz and removes the application...

Thank you btw...

**Comment by sevagas** [comment]
Your problem is that MImikatz is detected, you should work on recompile/obfuscate your MImikatz exe.
Also the bypass of Windows security support is done only for MacroPack Pro. You cannot ensure AV bypass support on a free/open source tool.
