### ISSUE TITLE
can someone help me to fix that ?

### ISSUE THREAD

**Issue by salahgeek** [sevagas/macro_pack#69]
└──╼ #pip3 install -r requirements.txt
Requirement already satisfied: colorama>=0.4.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.4)
Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: tabulate>=0.8.5 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (0.8.5)
Requirement already satisfied: psutil>=5.6.7 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (5.8.0)
Collecting clr>=1.0.3
  Using cached clr-1.0.3-py2.py3-none-any.whl (4.4 kB)
Collecting wsgidav>=3.0.0
  Using cached WsgiDAV-3.1.0-py2.py3-none-any.whl (174 kB)
Requirement already satisfied: cheroot>=6.3.3 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (8.5.2)
ERROR: Could not find a version that satisfies the requirement pywin32>=225
ERROR: No matching distribution found for pywin32>=225

**Comment by ceramic-skate0** [comment]
you have to manually type each missing package pip3 install {package}. thats what i did to fix

**Comment by sevagas** [comment]
@salahgeek have you installed on Windows? If you dont want to install on windows you have to remove pywin32 from the requirement

**Comment by sevagas** [comment]
No answer, I suppose this is closed.
