### ISSUE TITLE
appears to hang on [-] Rename API imports

### ISSUE THREAD

**Issue by ceramic-skate0** [sevagas/macro_pack#70]
Running on gadget2js payload (hta). the py and exe appears to hang (so far its been 30 min). 
![Capture](https://user-images.githubusercontent.com/64501203/119168465-ef3dd180-ba2e-11eb-9645-9ed879b09fac.PNG)

**Comment by ceramic-skate0** [comment]
appears to be same for vbs version as well

**Comment by sevagas** [comment]
Hi, Could you provide the command line input?

**Comment by ceramic-skate0** [comment]
left it alone for awhile longer screen shot of outcome attached
![Capture](https://user-images.githubusercontent.com/64501203/119348214-8e024200-bc6a-11eb-8e9c-e3e7f1ad77f7.PNG)

**Comment by ceramic-skate0** [comment]
command line is at bottom of terminal

**Comment by sevagas** [comment]
Hi, it seems you tried to use an hta file as input for MacroPack. MacroPack can only take a VBA file as input (or use the predefined templates).

**Comment by ceramic-skate0** [comment]
Re-tested with GadgetToJS VBA generated file. (Didnt rename hta file i actually generated the vba template). 
Same error output.
![Capture](https://user-images.githubusercontent.com/64501203/119712970-306b2280-be2f-11eb-88ee-1940363450c0.PNG)

**Comment by sevagas** [comment]
It seems the problem is MacroPack cannot find the start function in the VBA. 
Try do indicate the entry point using;
--start-function=START_FUNCTION

**Comment by sevagas** [comment]
@ceramic-skate0 , is it working when you set --start-function?

**Comment by ceramic-skate0** [comment]
thank you
