### ISSUE TITLE
How will this tool work?

### ISSUE THREAD

**Issue by ssl-user-en** [sevagas/macro_pack#72]
I'm struggling to make this tool work. How does this work. I downloaded the exe, i have the office installed.

Getting the following error:

'macro_pack.exe' is not recognized as an internal or external command,
operable program or batch file.

can anyone help me to run it.

**Comment by sevagas** [comment]
This is unusual. It cannot be a macro pack problem. Maybe the file was caught by your AV? Or some shareable folder issue.
