### ISSUE TITLE
couldnt report on my rat

### ISSUE THREAD

**Issue by 9993rills** [sevagas/macro_pack#74]
sucessfully created a clean doc file but dont report target on RAT

**Comment by sevagas** [comment]
Could you clarify what is the issue here? I do not understand. Also provide the command line you used to generate your payload and the scenario.

**Comment by 9993rills** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/84611223/131260053-6d888122-1ba2-4b3c-8788-42d5f76545de.png)

![Screenshot_4](https://user-images.githubusercontent.com/84611223/131260044-227340d2-c3ca-432c-ac5a-d32c4169cb6e.png)
Really admire package though! 
![Screenshot_1](https://user-images.githubusercontent.com/84611223/131259954-a8bee1e4-be44-4c95-9f44-1a5bed720089.png)
![Screenshot_3](https://user-images.githubusercontent.com/84611223/131260024-d94744eb-f16d-4093-86ec-028cb95716af.png)
![Screenshot_2](https://user-images.githubusercontent.com/84611223/131260032-bc261052-4499-479a-9452-b935a39d25dc.png)

**Comment by 9993rills** [comment]
kind lemme know if i'm missing anyting, thanks

**Comment by 9993rills** [comment]
solutions??

**Comment by sevagas** [comment]
Hi, is client.bin a VBA file? The only way it would work using this command line would be to use an input VBA file.
If client.bin is not a vba file, please read the README carefully and close this issue.

**Comment by 9993rills** [comment]
Thanks sevagas, client.bin is an EXE file, so according to "README" does that mean macro-pack will only work with pentesters' tools like metasploits, etc...? can i use on RAT application Build with visual studio 2019? what command do i use on exe?

**Comment by sevagas** [comment]
You can drop EXE with macro_pack.exe have a look at the DROPPER template for example, use --listtemplates to view the list of templates. You also have a list of example in the README file.
